name: 🤞 Build Editor!
on:
  # Manual
  workflow_dispatch:
    inputs:
      make-release:
        description: 'Make release'
        required: false
        type: boolean
        default: true

# Global Settings
# SCONS_CACHE for windows must be set in the build environment
env:
  # Used for cache key as well as for downloading the correct Godot version.
  GODOT_BRANCH: 3.x

jobs:
  windows:
    runs-on: "ubuntu-latest"
    name: Windows ${{ matrix.name }}
    env:
      SCONSFLAGS: use_mingw=yes
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Editor & Templates
            cache-name: windows
            build-mono: false

    steps:
      # region Setup
      - uses: actions/checkout@v3

      - name: Download Godot
        uses: ./.github/actions/godot-download
        with:
          version: ${{ env.GODOT_BRANCH }}

      - name: Linux dependencies
        shell: bash
        run: |
          sudo apt-get update
          # The actual dependencies
          sudo apt-get install build-essential pkg-config libx11-dev libxcursor-dev \
              libxinerama-dev libgl1-mesa-dev libglu-dev libasound2-dev libpulse-dev \
              libdbus-1-dev libudev-dev libxi-dev libxrandr-dev yasm xvfb unzip \
              libspeechd-dev speech-dispatcher libgl1-mesa-glx
          sudo apt-get -f install
      
      - name: Windows dependencies
        shell: bash
        run: |
          sudo apt-get install mingw-w64
          echo "1" | sudo update-alternatives --config x86_64-w64-mingw32-gcc
          echo "1" | sudo update-alternatives --config x86_64-w64-mingw32-g++
          echo "1" | sudo update-alternatives --config i686-w64-mingw32-gcc
          echo "1" | sudo update-alternatives --config i686-w64-mingw32-g++

      - name: Setup Godot build cache
        uses: ./.github/actions/godot-cache
        with:
          cache-name: ${{ matrix.cache-name }}
        continue-on-error: true

      - name: Setup python and scons
        uses: ./.github/actions/godot-deps
      # endregion

      # region Editor

      # region    (bits=64)
      - name: Compilation (bits=64)
        uses: ./.github/actions/godot-build
        with:
          sconsflags: ${{ env.SCONSFLAGS }} bits=64 ${{ matrix.build-mono && 'mono_prefix=$HOME/mono-installs/desktop-windows-x86_64-release' || '' }} debug_symbols=no
          platform: windows
          target: release_debug
          tools: true
          encryption-key: ${{ secrets.ENCRYPTION_KEY }}
      
      - name: Upload Editor
        uses: ./.github/actions/upload-artifact
        with:
          name: ${{ matrix.cache-name }}-editor-64
      
      - name: Clear bin
        run: |
          rm -rf bin
      # endregion
      # endregion

 
  create-release:
    if: success() && (
        (github.event_name == 'push') ||
        (github.event_name == 'schedule') ||
        (github.event_name == 'workflow_dispatch' && inputs.make-release)
      )
    needs: [windows]
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag-name.outputs.tag }}
    steps:
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Short SHA
        id: short-sha
        run: echo "sha7=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_OUTPUT
      
      - name: Tag Name
        id: tag-name
        run: echo "tag=Release-${{ steps.date.outputs.date }}-${{ steps.short-sha.outputs.sha7 }}" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag-name.outputs.tag }}
          name: Release ${{ steps.date.outputs.date }} #${{ steps.short-sha.outputs.sha7 }}
          draft: false
          prerelease: false

  upload-release-artifacts: 
    if: success() && (
        (github.event_name == 'push') ||
        (github.event_name == 'schedule') ||
        (github.event_name == 'workflow_dispatch' && inputs.make-release)
      )
    needs: create-release
    name: Upload Release Artifacts
    runs-on: ubuntu-latest
    strategy:
      matrix:
        artifact_name: [
          windows-editor-64,
        ]
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ matrix.artifact_name }}
          path: ./${{ matrix.artifact_name }}
      
      - name: Zip Artifact
        run: |
          original_path=$(pwd)
          pushd ${{ matrix.artifact_name }}
          zip -ry ${original_path}/${{ matrix.artifact_name }}.zip *
          popd

      - name: Debug
        shell: bash
        run: ls

      - name: Upload Artifact
        uses: softprops/action-gh-release@v0.1.15
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.create-release.outputs.tag }}
          files: ./${{ matrix.artifact_name }}.zip